package tools.networking.gui;
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tony
 */
public class net_tools extends javax.swing.JFrame {
    String extraction_path = null;
    String[] info, subnets[];
    
    /**
     * Creates new form net_tools
     */
    public net_tools() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_jpanel = new javax.swing.JPanel();
        top_jpanel = new javax.swing.JPanel();
        subnet_calc_button = new javax.swing.JButton();
        net_sum_button = new javax.swing.JButton();
        cidr_button = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        subnet_calc_jpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ip_textfield = new javax.swing.JTextField();
        mask_textfield = new javax.swing.JTextField();
        generate_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        masbits_textfield = new javax.swing.JTextField();
        hostbits_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subnets_textfield = new javax.swing.JTextField();
        hosts_textfield = new javax.swing.JTextField();
        bitmask_textfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        error_jlabel = new javax.swing.JLabel();
        export_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subnet_textarea = new javax.swing.JTextArea();
        cidr_jpanel = new javax.swing.JPanel();
        cidr_ip_textfield = new javax.swing.JTextField();
        cidr_mask_textfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cidr_generate_button = new javax.swing.JButton();
        cidr_result_textfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cidr_error_jlabel = new javax.swing.JLabel();
        summarization_jpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        main_jpanel.setBackground(new java.awt.Color(153, 153, 153));
        main_jpanel.setMinimumSize(new java.awt.Dimension(100, 600));
        main_jpanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        top_jpanel.setBackground(new java.awt.Color(51, 51, 51));

        subnet_calc_button.setBackground(new java.awt.Color(153, 153, 153));
        subnet_calc_button.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        subnet_calc_button.setText("Subnet Calculator");
        subnet_calc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subnet_calc_buttonActionPerformed(evt);
            }
        });

        net_sum_button.setBackground(new java.awt.Color(153, 153, 153));
        net_sum_button.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        net_sum_button.setText("Network Summarization");
        net_sum_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                net_sum_buttonActionPerformed(evt);
            }
        });

        cidr_button.setBackground(new java.awt.Color(153, 153, 153));
        cidr_button.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cidr_button.setText("CIDR Calculator");
        cidr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidr_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout top_jpanelLayout = new javax.swing.GroupLayout(top_jpanel);
        top_jpanel.setLayout(top_jpanelLayout);
        top_jpanelLayout.setHorizontalGroup(
            top_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_jpanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(subnet_calc_button)
                .addGap(148, 148, 148)
                .addComponent(cidr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(net_sum_button)
                .addGap(91, 91, 91))
        );
        top_jpanelLayout.setVerticalGroup(
            top_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_jpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(top_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subnet_calc_button)
                    .addComponent(net_sum_button)
                    .addComponent(cidr_button))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        subnet_calc_jpanel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("IP Address");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Subnet Mask");

        ip_textfield.setBackground(new java.awt.Color(51, 51, 51));
        ip_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ip_textfield.setForeground(new java.awt.Color(255, 255, 255));
        ip_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        mask_textfield.setBackground(new java.awt.Color(51, 51, 51));
        mask_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        mask_textfield.setForeground(new java.awt.Color(255, 255, 255));
        mask_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        generate_button.setBackground(new java.awt.Color(0, 0, 0));
        generate_button.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        generate_button.setForeground(new java.awt.Color(255, 255, 255));
        generate_button.setText("Generate");
        generate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("Mask Bits");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Host Bits");

        masbits_textfield.setEditable(false);
        masbits_textfield.setBackground(new java.awt.Color(51, 51, 51));
        masbits_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        masbits_textfield.setForeground(new java.awt.Color(255, 255, 255));

        hostbits_textfield.setEditable(false);
        hostbits_textfield.setBackground(new java.awt.Color(51, 51, 51));
        hostbits_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        hostbits_textfield.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel5.setText("Number of Subnets");

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("Hosts per Subnet");

        subnets_textfield.setEditable(false);
        subnets_textfield.setBackground(new java.awt.Color(51, 51, 51));
        subnets_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        subnets_textfield.setForeground(new java.awt.Color(255, 255, 255));

        hosts_textfield.setEditable(false);
        hosts_textfield.setBackground(new java.awt.Color(51, 51, 51));
        hosts_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        hosts_textfield.setForeground(new java.awt.Color(255, 255, 255));

        bitmask_textfield.setEditable(false);
        bitmask_textfield.setBackground(new java.awt.Color(51, 51, 51));
        bitmask_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        bitmask_textfield.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("Subnet Bit Mask");

        error_jlabel.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        error_jlabel.setForeground(new java.awt.Color(204, 0, 0));

        export_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        export_button.setBorder(null);
        export_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_buttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel11.setText("Export");

        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0)); //custome code to hide scrollbar

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Subnet");

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel9.setText("Host Range");

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("Broadcast");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addGap(355, 355, 355)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 318, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addComponent(jLabel10))
        );

        subnet_textarea.setEditable(false);
        subnet_textarea.setBackground(new java.awt.Color(51, 51, 51));
        subnet_textarea.setColumns(20);
        subnet_textarea.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        subnet_textarea.setForeground(new java.awt.Color(255, 255, 255));
        subnet_textarea.setRows(5);
        subnet_textarea.setBorder(null);
        jScrollPane3.setViewportView(subnet_textarea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout subnet_calc_jpanelLayout = new javax.swing.GroupLayout(subnet_calc_jpanel);
        subnet_calc_jpanel.setLayout(subnet_calc_jpanelLayout);
        subnet_calc_jpanelLayout.setHorizontalGroup(
            subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                                .addComponent(masbits_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                                .addComponent(hostbits_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subnets_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                                .addComponent(hosts_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(bitmask_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mask_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(generate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(error_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subnet_calc_jpanelLayout.createSequentialGroup()
                                .addComponent(export_button)
                                .addGap(13, 13, 13))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))))
            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        subnet_calc_jpanelLayout.setVerticalGroup(
            subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generate_button)
                            .addComponent(error_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(export_button)
                            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel11))
                            .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(mask_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(masbits_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subnet_calc_jpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subnets_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hostbits_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bitmask_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(subnet_calc_jpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(subnet_calc_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hosts_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", subnet_calc_jpanel);

        cidr_jpanel.setBackground(new java.awt.Color(153, 153, 153));

        cidr_ip_textfield.setBackground(new java.awt.Color(51, 51, 51));
        cidr_ip_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cidr_ip_textfield.setForeground(new java.awt.Color(255, 255, 255));
        cidr_ip_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cidr_mask_textfield.setBackground(new java.awt.Color(51, 51, 51));
        cidr_mask_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cidr_mask_textfield.setForeground(new java.awt.Color(255, 255, 255));
        cidr_mask_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("IP Address");

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel13.setText("Subnet Mask");

        cidr_generate_button.setBackground(new java.awt.Color(0, 0, 0));
        cidr_generate_button.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cidr_generate_button.setForeground(new java.awt.Color(255, 255, 255));
        cidr_generate_button.setText("Generate");
        cidr_generate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidr_generate_buttonActionPerformed(evt);
            }
        });

        cidr_result_textfield.setEditable(false);
        cidr_result_textfield.setBackground(new java.awt.Color(51, 51, 51));
        cidr_result_textfield.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cidr_result_textfield.setForeground(new java.awt.Color(255, 255, 255));
        cidr_result_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel14.setText("Subnet");

        jLabel15.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel15.setText("Host Range");

        jLabel16.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel16.setText("Broadcast");

        cidr_error_jlabel.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cidr_error_jlabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout cidr_jpanelLayout = new javax.swing.GroupLayout(cidr_jpanel);
        cidr_jpanel.setLayout(cidr_jpanelLayout);
        cidr_jpanelLayout.setHorizontalGroup(
            cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cidr_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cidr_jpanelLayout.createSequentialGroup()
                        .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidr_ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidr_mask_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(cidr_generate_button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cidr_error_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cidr_jpanelLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel14)
                            .addGap(285, 285, 285)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16))
                        .addComponent(cidr_result_textfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        cidr_jpanelLayout.setVerticalGroup(
            cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cidr_jpanelLayout.createSequentialGroup()
                .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cidr_jpanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidr_ip_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidr_mask_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(cidr_jpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cidr_error_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidr_generate_button))))
                .addGap(153, 153, 153)
                .addGroup(cidr_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(cidr_result_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", cidr_jpanel);

        summarization_jpanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout summarization_jpanelLayout = new javax.swing.GroupLayout(summarization_jpanel);
        summarization_jpanel.setLayout(summarization_jpanelLayout);
        summarization_jpanelLayout.setHorizontalGroup(
            summarization_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        summarization_jpanelLayout.setVerticalGroup(
            summarization_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", summarization_jpanel);

        javax.swing.GroupLayout main_jpanelLayout = new javax.swing.GroupLayout(main_jpanel);
        main_jpanel.setLayout(main_jpanelLayout);
        main_jpanelLayout.setHorizontalGroup(
            main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_jpanelLayout.createSequentialGroup()
                .addGroup(main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(top_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        main_jpanelLayout.setVerticalGroup(
            main_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_jpanelLayout.createSequentialGroup()
                .addComponent(top_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subnet_calc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subnet_calc_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_subnet_calc_buttonActionPerformed

    private void net_sum_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_net_sum_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_net_sum_buttonActionPerformed

    private void cidr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidr_buttonActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_cidr_buttonActionPerformed

    private void generate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_buttonActionPerformed
        String ip = ip_textfield.getText();
        String mask = mask_textfield.getText();
        String code;
        
        error_jlabel.setText("");
        
        classfull_subnetting c = new classfull_subnetting(ip,mask);
        code = c.check();

        if (code.equals("0")){
            info = c.getinfo();
            
            setinfotextfields(info);
            
            if(Integer.parseInt(info[3]) > 65536){
                error_jlabel.setText("Too many subnets to print, try exporting");
                subnet_textarea.setText("");
            }else{
                subnets=c.gen();
                settextarea(info,subnets);
            }
        }else{
            error(code);
        }
    }//GEN-LAST:event_generate_buttonActionPerformed

    private void export_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_buttonActionPerformed
        String ip = ip_textfield.getText();
        String mask = mask_textfield.getText();
        String code;


        error_jlabel.setText("");

        classfull_subnetting c = new classfull_subnetting(ip,mask);
        code = c.check();
        
        if (code.equals("0")){
            
            if (extraction_path == null) //check if path is empty
                getexpath(); //get extraction path

           if( info == null || Integer.parseInt(info[3]) > 65636 ){
               
               error_jlabel.setText("Exporting...");
               c.writer(extraction_path);

               error_jlabel.setText("File exported!");
               
               subnet_textarea.setText("");
               masbits_textfield.setText("");
               hostbits_textfield.setText("");
               subnets_textfield.setText("");
               hosts_textfield.setText("");
               bitmask_textfield.setText("");
                             
           }else{
               writetofile(info,subnets);
           }
           
        }else{
            error(code);
        }
    }//GEN-LAST:event_export_buttonActionPerformed

    private void cidr_generate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidr_generate_buttonActionPerformed

        String cidr_ip = cidr_ip_textfield.getText();
        String cidr_mask = cidr_mask_textfield.getText();
        
        cidr ci = new cidr(cidr_ip, cidr_mask);
        
        String result = ci.check();

        cidr_error_jlabel.setText(result);
        
        if(result.equals(""))
            cidr_result_textfield.setText(ci.generate());
        
    }//GEN-LAST:event_cidr_generate_buttonActionPerformed

    void writetofile(String[] info, String[][] text){
        
        try{ //Create file
            
            File outputf = new File(extraction_path+"\\subnets.txt");
            outputf.createNewFile();

        }catch(Exception e){
            error_jlabel.setText("Error Creating file");
        }
        
        error_jlabel.setText("Writing to file...");
        
        try{//write to file
            FileWriter wr = new FileWriter(extraction_path+"\\subnets.txt");
            
            wr.write("Mask Bits : "+ info[0]+"\n");
            wr.write("Host Bits : "+ info[1]+"\n");
            wr.write("Number of Subnets : "+ info[3]+"\n");
            wr.write("Hosts per Subnet : "+ info[4]+"\n");
            wr.write("Subnet Bit Mask : "+ info[5]+"\n");
            
            wr.write("\n  \t Subnet\t\t\t\t Host Range\t\t\t\t Broadcast\n");
            
            for(int i=0; i< Integer.parseInt(info[3]); i++)
                wr.write((i+1) + "\t" + text[i][0] + "\t\t\t" + text[i][1] + "\t to \t" + text[i][2] + "\t\t\t" + text[i][3] + "\n");

            wr.close();
            
        }catch(Exception e){
            error_jlabel.setText("ERROR while writing to file");
        }
        
        error_jlabel.setText("File exported!");
    }
    
    void getexpath(){ //get extraction path
        try{
            JFileChooser ch = new JFileChooser();
            ch.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            ch.showOpenDialog(null);
            File f = ch.getSelectedFile();
            extraction_path = f.getAbsolutePath();
        }catch(Exception e){
        }
    }
    
    void settextarea(String[] info, String[][] text){
        subnet_textarea.setText("");
        for(int i = 0; i< Integer.parseInt(info[3]); i++ ){
            subnet_textarea.append((i+1) + "\t" + text[i][0] + "\t\t\t" + text[i][1] + "\t to \t" + text[i][2] + "\t\t\t" + text[i][3] + "\n");
        }
    }
    
    void setinfotextfields(String[] info){
        masbits_textfield.setText(info[0]);
        hostbits_textfield.setText(info[1]);
        subnets_textfield.setText(info[3]);
        hosts_textfield.setText(info[4]);
        bitmask_textfield.setText(info[5]);
    }
    
    void error(String code){
        // # 1 = wrong ip size
        // # 2 = wrong mask size
        // # 3 = out of boundaries ip
        // # 4 = out of boundaries mask
        // # 5 = mask format wrong
        if(code.equals("1"))
            error_jlabel.setText("Wrong Size of IP");
        else if(code.equals("2"))
            error_jlabel.setText("Wrong Size of Mask");
        else if(code.equals("3"))
            error_jlabel.setText("IP out of Boundaries");
        else if(code.equals("4"))
            error_jlabel.setText("Mask out of Boundaries");
        else if(code.equals("5"))
            error_jlabel.setText("Wrong Mask Format");
        else if (code.equals("6"))
            error_jlabel.setText("IP and Mask Classes don't match");
        else
            error_jlabel.setText("Error");
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(net_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(net_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(net_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(net_tools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new net_tools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bitmask_textfield;
    private javax.swing.JButton cidr_button;
    private javax.swing.JLabel cidr_error_jlabel;
    private javax.swing.JButton cidr_generate_button;
    private javax.swing.JTextField cidr_ip_textfield;
    private javax.swing.JPanel cidr_jpanel;
    private javax.swing.JTextField cidr_mask_textfield;
    private javax.swing.JTextField cidr_result_textfield;
    private javax.swing.JLabel error_jlabel;
    private javax.swing.JButton export_button;
    private javax.swing.JButton generate_button;
    private javax.swing.JTextField hostbits_textfield;
    private javax.swing.JTextField hosts_textfield;
    private javax.swing.JTextField ip_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel main_jpanel;
    private javax.swing.JTextField masbits_textfield;
    private javax.swing.JTextField mask_textfield;
    private javax.swing.JButton net_sum_button;
    private javax.swing.JButton subnet_calc_button;
    private javax.swing.JPanel subnet_calc_jpanel;
    private javax.swing.JTextArea subnet_textarea;
    private javax.swing.JTextField subnets_textfield;
    private javax.swing.JPanel summarization_jpanel;
    private javax.swing.JPanel top_jpanel;
    // End of variables declaration//GEN-END:variables
}
